chore!: move to node 14 as minimum version
googleapis/node-gtoken pull request #457
Opened 2023-07-06 15:05 UTC by ddelgrosso1

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/node-gtoken/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2023-07-06 15:10 UTC, ddelgrosso1 commented
Need to make sure that https://github.com/googleapis/node-gtoken/pull/452 goes along with the upgrade / major version bump.

2023-07-10 19:37 UTC, sofisl approved these changes

2023-07-10 19:39 UTC, sofisl requested changes
I'd also remove the Node 12 folders in Kokoro, e.g.: https://github.com/googleapis/node-gtoken/tree/main/.kokoro/continuous/node12

2023-07-10 19:43 UTC, sofisl approved these changes

2023-07-11 20:31 UTC, merged